import "./globals.css";
import AnalyticsScripts from "./components/AnalyticsScripts";

// Auth
import { NextAuthProvider } from "./components/Providers";

// Styles & Design
import { Merriweather, Lora } from "next/font/google";

export const metadata = {
  title: "Untitled",
  description: "Generated by create next app",
};

const merriweather = Merriweather({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <AnalyticsScripts />
      <body className={merriweather.className}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
